AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function to Access External Endpoint

Parameters:
  AppName:
    Type: String
    Default: "MRGApp"
  ResourcePrefix:
    Type: String
    Default: "MRG"
  EndpointIp:
    Type: String
    Default: "203.0.113.0/24"

Resources:
  LambdaExternalEndpoint:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaCloudWatchLogsRole.Arn, !GetAtt LambdaSecretsManagerRole.Arn, !GetAtt LambdaSSMRole.Arn, !GetAtt LambdaS3Role.Arn, !GetAtt LambdaRDSRole.Arn , !GetAtt DBInstanceReadSecretRole.Arn
      Code:
        S3Bucket: !Sub "${ResourcePrefix}-lambda-code-bucket"
        S3Key: external_endpoint_lambda.zip
      Runtime: nodejs18.x
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PublicSubnet
      Environment:
        Variables:
          ENDPOINT_IP: !Ref EndpointIp
      Tags:
        - Key: Name
          Value: !Sub "${ResourcePrefix}-external-endpoint-lambda"
        - Key: Creator
          Value: !Ref AWS::AccountId
        - Key: App
          Value: !Ref AppName


