AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function to Access DB

Parameters:
  AppName:
    Type: String
    Default: "MRGApp"
  ResourcePrefix:
    Type: String
    Default: "MRG"
  Environment:
    Type: String
    Default: "ENV"


Resources:
  LambdaAccessDB:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaCloudWatchLogsRole.Arn, !GetAtt LambdaSecretsManagerRole.Arn, !GetAtt LambdaS3Role.Arn, !GetAtt LambdaRDSRole.Arn , !GetAtt LambdaReadSecretRole.Arn
      Code:
        S3Bucket: !Sub "${ResourcePrefix}-lambda-code-bucket"
        S3Key: access_db_lambda.zip
      Runtime: nodejs18.x
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet
      Environment:
        Variables:
          DB_SECRET_ARN: !ImportValue "arn:aws:secretsmanager:*:*:secret:${ResourcePrefix}-db-secret-*"
      Tags:
        - Key: Name
          Value: !Sub "${ResourcePrefix}-access-db-lambda"
        - Key: Creator
          Value: !Ref AWS::AccountId
        - Key: App
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
