AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager

Parameters:
  AppName:
    Type: String
    Default: "MRGApp"
  ResourcePrefix:
    Type: String
    Default: "MRG"

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${ResourcePrefix}-db-secret"
      SecretString: !Sub |
        {
          "username": "admin",
          "password": "p4ssg0rd.1987.))",
        }
      Tags:
        - Key: Name
          Value: !Sub "${ResourcePrefix}-db-secret"
        - Key: Creator
          Value: !Ref AWS::AccountId
        - Key: App
          Value: !Ref AppName
