Resources:
  S3Bucket: # Bucket de origen para CloudFront
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mybucket  # Reemplaza con tu nombre de bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  S3BucketPolicy: # Política para permitir acceso desde CloudFront
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${S3Bucket}/*
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
  
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: example.com  # Reemplaza con tu nombre de dominio real
      ValidationMethod: DNS  # Método de validación (DNS o EMAIL)
      SubjectAlternativeNames: # (Opcional) Nombres alternativos del sujeto (SANs)
        - www.example.com

  CloudFrontOriginAccessIdentity: # Identidad de origen para CloudFront
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access S3 bucket content only through CloudFront

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${S3Bucket}.s3.amazonaws.com
            Id: mybucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        Enabled: true
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: whitelist
              WhitelistedNames:
                - session_id # Ejemplo, personaliza según tu aplicación
          TargetOriginId: mybucket
        PriceClass: PriceClass_100 # Verifica si aplica a tu caso
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: false
          Bucket: myloggingbucket.s3.amazonaws.com
          Prefix: cloudfront/
